/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package example.customer;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

/** An example schema that represents a customer */
@org.apache.avro.specific.AvroGenerated
public class Customer extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 2055185778987891521L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Customer\",\"namespace\":\"example.customer\",\"doc\":\"An example schema that represents a customer\",\"fields\":[{\"name\":\"first_name\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"last_name\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"age\",\"type\":\"int\"},{\"name\":\"height\",\"type\":\"float\",\"doc\":\"in centimeters\"},{\"name\":\"weight\",\"type\":\"float\",\"doc\":\"in kilograms\"},{\"name\":\"automated_email\",\"type\":\"boolean\",\"default\":true},{\"name\":\"customer_emails\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},\"doc\":\"List of customer emails\",\"default\":[]},{\"name\":\"customer_address\",\"type\":{\"type\":\"record\",\"name\":\"CustomerAddress\",\"fields\":[{\"name\":\"address\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"the address\"},{\"name\":\"city\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"the city the address is located in\"},{\"name\":\"postal_code\",\"type\":[\"int\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"doc\":\"the postal code. Can be number of string\"}]},\"doc\":\"The address of the customer\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Customer> ENCODER =
      new BinaryMessageEncoder<Customer>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Customer> DECODER =
      new BinaryMessageDecoder<Customer>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Customer> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Customer> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Customer> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Customer>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Customer to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Customer from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Customer instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Customer fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.String first_name;
   private java.lang.String last_name;
   private int age;
  /** in centimeters */
   private float height;
  /** in kilograms */
   private float weight;
   private boolean automated_email;
  /** List of customer emails */
   private java.util.List<java.lang.String> customer_emails;
  /** The address of the customer */
   private example.customer.CustomerAddress customer_address;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Customer() {}

  /**
   * All-args constructor.
   * @param first_name The new value for first_name
   * @param last_name The new value for last_name
   * @param age The new value for age
   * @param height in centimeters
   * @param weight in kilograms
   * @param automated_email The new value for automated_email
   * @param customer_emails List of customer emails
   * @param customer_address The address of the customer
   */
  public Customer(java.lang.String first_name, java.lang.String last_name, java.lang.Integer age, java.lang.Float height, java.lang.Float weight, java.lang.Boolean automated_email, java.util.List<java.lang.String> customer_emails, example.customer.CustomerAddress customer_address) {
    this.first_name = first_name;
    this.last_name = last_name;
    this.age = age;
    this.height = height;
    this.weight = weight;
    this.automated_email = automated_email;
    this.customer_emails = customer_emails;
    this.customer_address = customer_address;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return first_name;
    case 1: return last_name;
    case 2: return age;
    case 3: return height;
    case 4: return weight;
    case 5: return automated_email;
    case 6: return customer_emails;
    case 7: return customer_address;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: first_name = value$ != null ? value$.toString() : null; break;
    case 1: last_name = value$ != null ? value$.toString() : null; break;
    case 2: age = (java.lang.Integer)value$; break;
    case 3: height = (java.lang.Float)value$; break;
    case 4: weight = (java.lang.Float)value$; break;
    case 5: automated_email = (java.lang.Boolean)value$; break;
    case 6: customer_emails = (java.util.List<java.lang.String>)value$; break;
    case 7: customer_address = (example.customer.CustomerAddress)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'first_name' field.
   * @return The value of the 'first_name' field.
   */
  public java.lang.String getFirstName() {
    return first_name;
  }



  /**
   * Gets the value of the 'last_name' field.
   * @return The value of the 'last_name' field.
   */
  public java.lang.String getLastName() {
    return last_name;
  }



  /**
   * Gets the value of the 'age' field.
   * @return The value of the 'age' field.
   */
  public int getAge() {
    return age;
  }



  /**
   * Gets the value of the 'height' field.
   * @return in centimeters
   */
  public float getHeight() {
    return height;
  }



  /**
   * Gets the value of the 'weight' field.
   * @return in kilograms
   */
  public float getWeight() {
    return weight;
  }



  /**
   * Gets the value of the 'automated_email' field.
   * @return The value of the 'automated_email' field.
   */
  public boolean getAutomatedEmail() {
    return automated_email;
  }



  /**
   * Gets the value of the 'customer_emails' field.
   * @return List of customer emails
   */
  public java.util.List<java.lang.String> getCustomerEmails() {
    return customer_emails;
  }



  /**
   * Gets the value of the 'customer_address' field.
   * @return The address of the customer
   */
  public example.customer.CustomerAddress getCustomerAddress() {
    return customer_address;
  }



  /**
   * Creates a new Customer RecordBuilder.
   * @return A new Customer RecordBuilder
   */
  public static example.customer.Customer.Builder newBuilder() {
    return new example.customer.Customer.Builder();
  }

  /**
   * Creates a new Customer RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Customer RecordBuilder
   */
  public static example.customer.Customer.Builder newBuilder(example.customer.Customer.Builder other) {
    if (other == null) {
      return new example.customer.Customer.Builder();
    } else {
      return new example.customer.Customer.Builder(other);
    }
  }

  /**
   * Creates a new Customer RecordBuilder by copying an existing Customer instance.
   * @param other The existing instance to copy.
   * @return A new Customer RecordBuilder
   */
  public static example.customer.Customer.Builder newBuilder(example.customer.Customer other) {
    if (other == null) {
      return new example.customer.Customer.Builder();
    } else {
      return new example.customer.Customer.Builder(other);
    }
  }

  /**
   * RecordBuilder for Customer instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Customer>
    implements org.apache.avro.data.RecordBuilder<Customer> {

    private java.lang.String first_name;
    private java.lang.String last_name;
    private int age;
    /** in centimeters */
    private float height;
    /** in kilograms */
    private float weight;
    private boolean automated_email;
    /** List of customer emails */
    private java.util.List<java.lang.String> customer_emails;
    /** The address of the customer */
    private example.customer.CustomerAddress customer_address;
    private example.customer.CustomerAddress.Builder customer_addressBuilder;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(example.customer.Customer.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.first_name)) {
        this.first_name = data().deepCopy(fields()[0].schema(), other.first_name);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.last_name)) {
        this.last_name = data().deepCopy(fields()[1].schema(), other.last_name);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.age)) {
        this.age = data().deepCopy(fields()[2].schema(), other.age);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.height)) {
        this.height = data().deepCopy(fields()[3].schema(), other.height);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.weight)) {
        this.weight = data().deepCopy(fields()[4].schema(), other.weight);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.automated_email)) {
        this.automated_email = data().deepCopy(fields()[5].schema(), other.automated_email);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.customer_emails)) {
        this.customer_emails = data().deepCopy(fields()[6].schema(), other.customer_emails);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.customer_address)) {
        this.customer_address = data().deepCopy(fields()[7].schema(), other.customer_address);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
      if (other.hasCustomerAddressBuilder()) {
        this.customer_addressBuilder = example.customer.CustomerAddress.newBuilder(other.getCustomerAddressBuilder());
      }
    }

    /**
     * Creates a Builder by copying an existing Customer instance
     * @param other The existing instance to copy.
     */
    private Builder(example.customer.Customer other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.first_name)) {
        this.first_name = data().deepCopy(fields()[0].schema(), other.first_name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.last_name)) {
        this.last_name = data().deepCopy(fields()[1].schema(), other.last_name);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.age)) {
        this.age = data().deepCopy(fields()[2].schema(), other.age);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.height)) {
        this.height = data().deepCopy(fields()[3].schema(), other.height);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.weight)) {
        this.weight = data().deepCopy(fields()[4].schema(), other.weight);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.automated_email)) {
        this.automated_email = data().deepCopy(fields()[5].schema(), other.automated_email);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.customer_emails)) {
        this.customer_emails = data().deepCopy(fields()[6].schema(), other.customer_emails);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.customer_address)) {
        this.customer_address = data().deepCopy(fields()[7].schema(), other.customer_address);
        fieldSetFlags()[7] = true;
      }
      this.customer_addressBuilder = null;
    }

    /**
      * Gets the value of the 'first_name' field.
      * @return The value.
      */
    public java.lang.String getFirstName() {
      return first_name;
    }


    /**
      * Sets the value of the 'first_name' field.
      * @param value The value of 'first_name'.
      * @return This builder.
      */
    public example.customer.Customer.Builder setFirstName(java.lang.String value) {
      validate(fields()[0], value);
      this.first_name = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'first_name' field has been set.
      * @return True if the 'first_name' field has been set, false otherwise.
      */
    public boolean hasFirstName() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'first_name' field.
      * @return This builder.
      */
    public example.customer.Customer.Builder clearFirstName() {
      first_name = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'last_name' field.
      * @return The value.
      */
    public java.lang.String getLastName() {
      return last_name;
    }


    /**
      * Sets the value of the 'last_name' field.
      * @param value The value of 'last_name'.
      * @return This builder.
      */
    public example.customer.Customer.Builder setLastName(java.lang.String value) {
      validate(fields()[1], value);
      this.last_name = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'last_name' field has been set.
      * @return True if the 'last_name' field has been set, false otherwise.
      */
    public boolean hasLastName() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'last_name' field.
      * @return This builder.
      */
    public example.customer.Customer.Builder clearLastName() {
      last_name = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'age' field.
      * @return The value.
      */
    public int getAge() {
      return age;
    }


    /**
      * Sets the value of the 'age' field.
      * @param value The value of 'age'.
      * @return This builder.
      */
    public example.customer.Customer.Builder setAge(int value) {
      validate(fields()[2], value);
      this.age = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'age' field has been set.
      * @return True if the 'age' field has been set, false otherwise.
      */
    public boolean hasAge() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'age' field.
      * @return This builder.
      */
    public example.customer.Customer.Builder clearAge() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'height' field.
      * in centimeters
      * @return The value.
      */
    public float getHeight() {
      return height;
    }


    /**
      * Sets the value of the 'height' field.
      * in centimeters
      * @param value The value of 'height'.
      * @return This builder.
      */
    public example.customer.Customer.Builder setHeight(float value) {
      validate(fields()[3], value);
      this.height = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'height' field has been set.
      * in centimeters
      * @return True if the 'height' field has been set, false otherwise.
      */
    public boolean hasHeight() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'height' field.
      * in centimeters
      * @return This builder.
      */
    public example.customer.Customer.Builder clearHeight() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'weight' field.
      * in kilograms
      * @return The value.
      */
    public float getWeight() {
      return weight;
    }


    /**
      * Sets the value of the 'weight' field.
      * in kilograms
      * @param value The value of 'weight'.
      * @return This builder.
      */
    public example.customer.Customer.Builder setWeight(float value) {
      validate(fields()[4], value);
      this.weight = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'weight' field has been set.
      * in kilograms
      * @return True if the 'weight' field has been set, false otherwise.
      */
    public boolean hasWeight() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'weight' field.
      * in kilograms
      * @return This builder.
      */
    public example.customer.Customer.Builder clearWeight() {
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'automated_email' field.
      * @return The value.
      */
    public boolean getAutomatedEmail() {
      return automated_email;
    }


    /**
      * Sets the value of the 'automated_email' field.
      * @param value The value of 'automated_email'.
      * @return This builder.
      */
    public example.customer.Customer.Builder setAutomatedEmail(boolean value) {
      validate(fields()[5], value);
      this.automated_email = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'automated_email' field has been set.
      * @return True if the 'automated_email' field has been set, false otherwise.
      */
    public boolean hasAutomatedEmail() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'automated_email' field.
      * @return This builder.
      */
    public example.customer.Customer.Builder clearAutomatedEmail() {
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'customer_emails' field.
      * List of customer emails
      * @return The value.
      */
    public java.util.List<java.lang.String> getCustomerEmails() {
      return customer_emails;
    }


    /**
      * Sets the value of the 'customer_emails' field.
      * List of customer emails
      * @param value The value of 'customer_emails'.
      * @return This builder.
      */
    public example.customer.Customer.Builder setCustomerEmails(java.util.List<java.lang.String> value) {
      validate(fields()[6], value);
      this.customer_emails = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'customer_emails' field has been set.
      * List of customer emails
      * @return True if the 'customer_emails' field has been set, false otherwise.
      */
    public boolean hasCustomerEmails() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'customer_emails' field.
      * List of customer emails
      * @return This builder.
      */
    public example.customer.Customer.Builder clearCustomerEmails() {
      customer_emails = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'customer_address' field.
      * The address of the customer
      * @return The value.
      */
    public example.customer.CustomerAddress getCustomerAddress() {
      return customer_address;
    }


    /**
      * Sets the value of the 'customer_address' field.
      * The address of the customer
      * @param value The value of 'customer_address'.
      * @return This builder.
      */
    public example.customer.Customer.Builder setCustomerAddress(example.customer.CustomerAddress value) {
      validate(fields()[7], value);
      this.customer_addressBuilder = null;
      this.customer_address = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'customer_address' field has been set.
      * The address of the customer
      * @return True if the 'customer_address' field has been set, false otherwise.
      */
    public boolean hasCustomerAddress() {
      return fieldSetFlags()[7];
    }

    /**
     * Gets the Builder instance for the 'customer_address' field and creates one if it doesn't exist yet.
     * The address of the customer
     * @return This builder.
     */
    public example.customer.CustomerAddress.Builder getCustomerAddressBuilder() {
      if (customer_addressBuilder == null) {
        if (hasCustomerAddress()) {
          setCustomerAddressBuilder(example.customer.CustomerAddress.newBuilder(customer_address));
        } else {
          setCustomerAddressBuilder(example.customer.CustomerAddress.newBuilder());
        }
      }
      return customer_addressBuilder;
    }

    /**
     * Sets the Builder instance for the 'customer_address' field
     * The address of the customer
     * @param value The builder instance that must be set.
     * @return This builder.
     */

    public example.customer.Customer.Builder setCustomerAddressBuilder(example.customer.CustomerAddress.Builder value) {
      clearCustomerAddress();
      customer_addressBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'customer_address' field has an active Builder instance
     * The address of the customer
     * @return True if the 'customer_address' field has an active Builder instance
     */
    public boolean hasCustomerAddressBuilder() {
      return customer_addressBuilder != null;
    }

    /**
      * Clears the value of the 'customer_address' field.
      * The address of the customer
      * @return This builder.
      */
    public example.customer.Customer.Builder clearCustomerAddress() {
      customer_address = null;
      customer_addressBuilder = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Customer build() {
      try {
        Customer record = new Customer();
        record.first_name = fieldSetFlags()[0] ? this.first_name : (java.lang.String) defaultValue(fields()[0]);
        record.last_name = fieldSetFlags()[1] ? this.last_name : (java.lang.String) defaultValue(fields()[1]);
        record.age = fieldSetFlags()[2] ? this.age : (java.lang.Integer) defaultValue(fields()[2]);
        record.height = fieldSetFlags()[3] ? this.height : (java.lang.Float) defaultValue(fields()[3]);
        record.weight = fieldSetFlags()[4] ? this.weight : (java.lang.Float) defaultValue(fields()[4]);
        record.automated_email = fieldSetFlags()[5] ? this.automated_email : (java.lang.Boolean) defaultValue(fields()[5]);
        record.customer_emails = fieldSetFlags()[6] ? this.customer_emails : (java.util.List<java.lang.String>) defaultValue(fields()[6]);
        if (customer_addressBuilder != null) {
          try {
            record.customer_address = this.customer_addressBuilder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("customer_address"));
            throw e;
          }
        } else {
          record.customer_address = fieldSetFlags()[7] ? this.customer_address : (example.customer.CustomerAddress) defaultValue(fields()[7]);
        }
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Customer>
    WRITER$ = (org.apache.avro.io.DatumWriter<Customer>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Customer>
    READER$ = (org.apache.avro.io.DatumReader<Customer>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










