/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package example.customer;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class CustomerAddress extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 8368743876485244703L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"CustomerAddress\",\"namespace\":\"example.customer\",\"fields\":[{\"name\":\"address\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"the address\"},{\"name\":\"city\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"the city the address is located in\"},{\"name\":\"postal_code\",\"type\":[\"int\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"doc\":\"the postal code. Can be number of string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<CustomerAddress> ENCODER =
      new BinaryMessageEncoder<CustomerAddress>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<CustomerAddress> DECODER =
      new BinaryMessageDecoder<CustomerAddress>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<CustomerAddress> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<CustomerAddress> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<CustomerAddress> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<CustomerAddress>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this CustomerAddress to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a CustomerAddress from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a CustomerAddress instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static CustomerAddress fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** the address */
   private java.lang.String address;
  /** the city the address is located in */
   private java.lang.String city;
  /** the postal code. Can be number of string */
   private java.lang.Object postal_code;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public CustomerAddress() {}

  /**
   * All-args constructor.
   * @param address the address
   * @param city the city the address is located in
   * @param postal_code the postal code. Can be number of string
   */
  public CustomerAddress(java.lang.String address, java.lang.String city, java.lang.Object postal_code) {
    this.address = address;
    this.city = city;
    this.postal_code = postal_code;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return address;
    case 1: return city;
    case 2: return postal_code;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: address = value$ != null ? value$.toString() : null; break;
    case 1: city = value$ != null ? value$.toString() : null; break;
    case 2: postal_code = value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'address' field.
   * @return the address
   */
  public java.lang.String getAddress() {
    return address;
  }



  /**
   * Gets the value of the 'city' field.
   * @return the city the address is located in
   */
  public java.lang.String getCity() {
    return city;
  }



  /**
   * Gets the value of the 'postal_code' field.
   * @return the postal code. Can be number of string
   */
  public java.lang.Object getPostalCode() {
    return postal_code;
  }



  /**
   * Creates a new CustomerAddress RecordBuilder.
   * @return A new CustomerAddress RecordBuilder
   */
  public static example.customer.CustomerAddress.Builder newBuilder() {
    return new example.customer.CustomerAddress.Builder();
  }

  /**
   * Creates a new CustomerAddress RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new CustomerAddress RecordBuilder
   */
  public static example.customer.CustomerAddress.Builder newBuilder(example.customer.CustomerAddress.Builder other) {
    if (other == null) {
      return new example.customer.CustomerAddress.Builder();
    } else {
      return new example.customer.CustomerAddress.Builder(other);
    }
  }

  /**
   * Creates a new CustomerAddress RecordBuilder by copying an existing CustomerAddress instance.
   * @param other The existing instance to copy.
   * @return A new CustomerAddress RecordBuilder
   */
  public static example.customer.CustomerAddress.Builder newBuilder(example.customer.CustomerAddress other) {
    if (other == null) {
      return new example.customer.CustomerAddress.Builder();
    } else {
      return new example.customer.CustomerAddress.Builder(other);
    }
  }

  /**
   * RecordBuilder for CustomerAddress instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<CustomerAddress>
    implements org.apache.avro.data.RecordBuilder<CustomerAddress> {

    /** the address */
    private java.lang.String address;
    /** the city the address is located in */
    private java.lang.String city;
    /** the postal code. Can be number of string */
    private java.lang.Object postal_code;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(example.customer.CustomerAddress.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.address)) {
        this.address = data().deepCopy(fields()[0].schema(), other.address);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.city)) {
        this.city = data().deepCopy(fields()[1].schema(), other.city);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.postal_code)) {
        this.postal_code = data().deepCopy(fields()[2].schema(), other.postal_code);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing CustomerAddress instance
     * @param other The existing instance to copy.
     */
    private Builder(example.customer.CustomerAddress other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.address)) {
        this.address = data().deepCopy(fields()[0].schema(), other.address);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.city)) {
        this.city = data().deepCopy(fields()[1].schema(), other.city);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.postal_code)) {
        this.postal_code = data().deepCopy(fields()[2].schema(), other.postal_code);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'address' field.
      * the address
      * @return The value.
      */
    public java.lang.String getAddress() {
      return address;
    }


    /**
      * Sets the value of the 'address' field.
      * the address
      * @param value The value of 'address'.
      * @return This builder.
      */
    public example.customer.CustomerAddress.Builder setAddress(java.lang.String value) {
      validate(fields()[0], value);
      this.address = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'address' field has been set.
      * the address
      * @return True if the 'address' field has been set, false otherwise.
      */
    public boolean hasAddress() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'address' field.
      * the address
      * @return This builder.
      */
    public example.customer.CustomerAddress.Builder clearAddress() {
      address = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'city' field.
      * the city the address is located in
      * @return The value.
      */
    public java.lang.String getCity() {
      return city;
    }


    /**
      * Sets the value of the 'city' field.
      * the city the address is located in
      * @param value The value of 'city'.
      * @return This builder.
      */
    public example.customer.CustomerAddress.Builder setCity(java.lang.String value) {
      validate(fields()[1], value);
      this.city = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'city' field has been set.
      * the city the address is located in
      * @return True if the 'city' field has been set, false otherwise.
      */
    public boolean hasCity() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'city' field.
      * the city the address is located in
      * @return This builder.
      */
    public example.customer.CustomerAddress.Builder clearCity() {
      city = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'postal_code' field.
      * the postal code. Can be number of string
      * @return The value.
      */
    public java.lang.Object getPostalCode() {
      return postal_code;
    }


    /**
      * Sets the value of the 'postal_code' field.
      * the postal code. Can be number of string
      * @param value The value of 'postal_code'.
      * @return This builder.
      */
    public example.customer.CustomerAddress.Builder setPostalCode(java.lang.Object value) {
      validate(fields()[2], value);
      this.postal_code = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'postal_code' field has been set.
      * the postal code. Can be number of string
      * @return True if the 'postal_code' field has been set, false otherwise.
      */
    public boolean hasPostalCode() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'postal_code' field.
      * the postal code. Can be number of string
      * @return This builder.
      */
    public example.customer.CustomerAddress.Builder clearPostalCode() {
      postal_code = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public CustomerAddress build() {
      try {
        CustomerAddress record = new CustomerAddress();
        record.address = fieldSetFlags()[0] ? this.address : (java.lang.String) defaultValue(fields()[0]);
        record.city = fieldSetFlags()[1] ? this.city : (java.lang.String) defaultValue(fields()[1]);
        record.postal_code = fieldSetFlags()[2] ? this.postal_code :  defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<CustomerAddress>
    WRITER$ = (org.apache.avro.io.DatumWriter<CustomerAddress>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<CustomerAddress>
    READER$ = (org.apache.avro.io.DatumReader<CustomerAddress>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










